package com.zhenningtech.leaning.equipment.model;

import java.math.BigDecimal;

public class Equipment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.id
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.type
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.name
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.position_x
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    private BigDecimal positionX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.position_y
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    private BigDecimal positionY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.volumn
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    private String volumn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.id
     *
     * @return the value of equipment.id
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.id
     *
     * @param id the value for equipment.id
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.type
     *
     * @return the value of equipment.type
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.type
     *
     * @param type the value for equipment.type
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.name
     *
     * @return the value of equipment.name
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.name
     *
     * @param name the value for equipment.name
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.position_x
     *
     * @return the value of equipment.position_x
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public BigDecimal getPositionX() {
        return positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.position_x
     *
     * @param positionX the value for equipment.position_x
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public void setPositionX(BigDecimal positionX) {
        this.positionX = positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.position_y
     *
     * @return the value of equipment.position_y
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public BigDecimal getPositionY() {
        return positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.position_y
     *
     * @param positionY the value for equipment.position_y
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public void setPositionY(BigDecimal positionY) {
        this.positionY = positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.volumn
     *
     * @return the value of equipment.volumn
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public String getVolumn() {
        return volumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.volumn
     *
     * @param volumn the value for equipment.volumn
     *
     * @mbg.generated Fri Mar 01 10:00:22 CST 2019
     */
    public void setVolumn(String volumn) {
        this.volumn = volumn;
    }
}