package com.zhenningtech.leaning.system.mapper;

import com.zhenningtech.leaning.system.model.SystemMenu;
import java.util.List;

public interface SystemMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	int insert(SystemMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	SystemMenu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	List<SystemMenu> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table system_menu
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	int updateByPrimaryKey(SystemMenu record);

	List<SystemMenu> selectAllInuse();
}