package com.zhenningtech.leaning.system.model;

public class SystemMenu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_menu.id
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_menu.name
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_menu.action
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	private String action;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_menu.p_id
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	private Integer pId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_menu.status
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	private Boolean status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_menu.id
	 * @return  the value of system_menu.id
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_menu.id
	 * @param id  the value for system_menu.id
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_menu.name
	 * @return  the value of system_menu.name
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_menu.name
	 * @param name  the value for system_menu.name
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_menu.action
	 * @return  the value of system_menu.action
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	public String getAction() {
		return action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_menu.action
	 * @param action  the value for system_menu.action
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_menu.p_id
	 * @return  the value of system_menu.p_id
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	public Integer getpId() {
		return pId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_menu.p_id
	 * @param pId  the value for system_menu.p_id
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	public void setpId(Integer pId) {
		this.pId = pId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_menu.status
	 * @return  the value of system_menu.status
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_menu.status
	 * @param status  the value for system_menu.status
	 * @mbg.generated  Thu Mar 28 11:50:55 CST 2019
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}
}