package com.zhenningtech.leaning.basic.model;

public class BasicEquipmentPicture {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment_picture.id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment_picture.equipment_id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Integer equipmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment_picture.attachment_id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Integer attachmentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment_picture.id
	 * @return  the value of basic_equipment_picture.id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment_picture.id
	 * @param id  the value for basic_equipment_picture.id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment_picture.equipment_id
	 * @return  the value of basic_equipment_picture.equipment_id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Integer getEquipmentId() {
		return equipmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment_picture.equipment_id
	 * @param equipmentId  the value for basic_equipment_picture.equipment_id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setEquipmentId(Integer equipmentId) {
		this.equipmentId = equipmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment_picture.attachment_id
	 * @return  the value of basic_equipment_picture.attachment_id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Integer getAttachmentId() {
		return attachmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment_picture.attachment_id
	 * @param attachmentId  the value for basic_equipment_picture.attachment_id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}
}