package com.zhenningtech.leaning.basic.model;

public class BasicCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_category.id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_category.code
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_category.name
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_category.parent_id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_category.status
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Boolean status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_category.deleted
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Integer deleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_category.description
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_category.id
	 * @return  the value of basic_category.id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_category.id
	 * @param id  the value for basic_category.id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_category.code
	 * @return  the value of basic_category.code
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_category.code
	 * @param code  the value for basic_category.code
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_category.name
	 * @return  the value of basic_category.name
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_category.name
	 * @param name  the value for basic_category.name
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_category.parent_id
	 * @return  the value of basic_category.parent_id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_category.parent_id
	 * @param parentId  the value for basic_category.parent_id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_category.status
	 * @return  the value of basic_category.status
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_category.status
	 * @param status  the value for basic_category.status
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_category.deleted
	 * @return  the value of basic_category.deleted
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Integer getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_category.deleted
	 * @param deleted  the value for basic_category.deleted
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_category.description
	 * @return  the value of basic_category.description
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_category.description
	 * @param description  the value for basic_category.description
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}