package com.zhenningtech.leaning.basic.model;

import java.util.List;

public class BasicEquipment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment.id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment.no
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment.name
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment.category
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Integer category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment.type
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment.address
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment.status
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Boolean status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment.deleted
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private Integer deleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment.username
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment.password
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column basic_equipment.description
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment.id
	 * @return  the value of basic_equipment.id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment.id
	 * @param id  the value for basic_equipment.id
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment.no
	 * @return  the value of basic_equipment.no
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment.no
	 * @param no  the value for basic_equipment.no
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setNo(String no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment.name
	 * @return  the value of basic_equipment.name
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment.name
	 * @param name  the value for basic_equipment.name
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment.category
	 * @return  the value of basic_equipment.category
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Integer getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment.category
	 * @param category  the value for basic_equipment.category
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setCategory(Integer category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment.type
	 * @return  the value of basic_equipment.type
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment.type
	 * @param type  the value for basic_equipment.type
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment.address
	 * @return  the value of basic_equipment.address
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment.address
	 * @param address  the value for basic_equipment.address
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment.status
	 * @return  the value of basic_equipment.status
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment.status
	 * @param status  the value for basic_equipment.status
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment.deleted
	 * @return  the value of basic_equipment.deleted
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public Integer getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment.deleted
	 * @param deleted  the value for basic_equipment.deleted
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment.username
	 * @return  the value of basic_equipment.username
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment.username
	 * @param username  the value for basic_equipment.username
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment.password
	 * @return  the value of basic_equipment.password
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment.password
	 * @param password  the value for basic_equipment.password
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column basic_equipment.description
	 * @return  the value of basic_equipment.description
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column basic_equipment.description
	 * @param description  the value for basic_equipment.description
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	private List<BasicEquipment> children;
	
	private String categoryName;

	public List<BasicEquipment> getChildren() {
		return children;
	}

	public void setChildren(List<BasicEquipment> children) {
		this.children = children;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

}