package com.zhenningtech.leaning.basic.mapper;

import com.zhenningtech.leaning.basic.model.BasicCategory;
import java.util.List;

public interface BasicCategoryMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basic_category
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basic_category
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	int insert(BasicCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basic_category
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	BasicCategory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basic_category
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	List<BasicCategory> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table basic_category
	 * @mbg.generated  Wed Apr 03 09:31:47 CST 2019
	 */
	int updateByPrimaryKey(BasicCategory record);

	int updateByPrimaryKeyWithoutDeleted(BasicCategory record);
	
	List<BasicCategory> selectWithoutDeleted();
	
	int insertGeneratorKey(BasicCategory record);

	int deleteByPrimaryKeyLogic(Integer id);
}